name: StormBit IRC Network
description: "StormBit is an IRC network dedicated to anything you can think of from open source projects, to video games, to anime culture, we have a little of every community, so you can feel right at home. We also strongly believe in free speech and take a very hands-off approach to moderation, so if you can't find a channel that suits you, come on and make one!"
keywords: IRC, stormbit, anime, gaming, chat

paginate: 3,
paginate_path: /page:num

url: http://stormbit.net/
base: http://stormbit.net/
tld: stormbit.net

permalink: /:year/:month/:day/:title.html

encoding: UTF-8

markdown: redcarpet
redcarpet:
 extensions: [
  "no_intra_emphasis",
  "fenced_code_blocks",
  "tables",
  "strikethrough"
 ]
pygments: false

# if you change the indents here, also fix it in the Rakefile!
people:
  amethyst:
    name: Amethyst
    email:
    nick: amethyst
    website:
    twitter:
    gravatar:
    location:
    role:
  antoligy:
    name: Alex Wilson
    email: alex.w@stormbit.net
    nick: nekoflan
    website: http://antoligy.com/
    twitter: antoligy
    gravatar: a38b4c49423da71c55cec5b9482a682f
    location: West Midlands, England
    role: Network Owner
  angelXwind:
    name: Karen Tsai
    email: alex.w@stormbit.net
    nick: angelXwind
    website: http://angelxwind.net/
    twitter: angelXwind
    gravatar: e7ec1508da6f89b3b971aa93d194b0b1
    location: New York, USA
    role: Network Adminstrator
  benbop:
    name: Ben Hale
    email: benbop@antoligy.com
    nick: benbop
    website:
    twitter: benbop1992
    gravatar: 5b1856bc156e2e3ee51f74fb126ca846
    location: Walsall, UK
    role: Network Technician
  clarjon1:
    name: Jonathan Clark
    email: clarjon1@xfilescabinet.com
    nick: clarjon1
    website: http://xfilescabinet.com/
    twitter:
    gravatar: 8c9d9726112273515de7113661afcc48
    location: Ontario, Canada
    role: Network Technician
  dj_arghlex:
    name: Alex Mitchell
    email:
    nick: dj_arghlex
    website: http://arghlex.net/
    twitter:
    gravatar:
    location: Washington, USA
    role: Network Technician
  mikotohe2:
    name: Lucy Firman
    email: lucy.f@stormbit.net
    nick: lucy
    twitter: mikotohe2
    gravatar: 32704faf83d4752c5cec2e918557409b
    location: Essex, England
    role: Network Officer
  reimuhakurei:
    name: Alex Ingram
    email: alex.i@stormbit.net
    nick: reimuhakurei
    website: http://reimuhakurei.net/
    twitter: kudo147
    gravatar:
    location: Indiana, USA
    role: Network Administrator
  rikai:
    name: Mathew Rupp
    email:
    nick: rikai
    website: http://rikairchy.net/
    twitter:
    gravatar:
    location: North Carolina, USA
    role: Network Technician
  tiffany:
    name: Tiffany Bennett
    email: tiffany@stormbit.net
    nick: tiffany
    website: http://lymiahugs.com/~tiffany
    twitter: tiffany_public
    gravatar: 8ca0ebe649d1a7cb609b53d540b05f52
    location: Florida, USA
    role: Network Technician
