name: StormBit IRC Network
description: >
 StormBit is an IRC network dedicated to anything you can think of from open source projects, to
 video games, to anime culture, we have a little of every community, so you can feel right at home.
 We also strongly believe in free speech and take a very hands-off approach to moderation, so if
 you can't find a channel that suits you, come on and make one!
keywords: IRC, stormbit, anime, gaming, chat

paginate: 3
paginate_path: /page:num

url: http://stormbit.net/
base: http://stormbit.net/
tld: stormbit.net

permalink: /:year/:month/:day/:title.html

encoding: UTF-8

markdown: redcarpet
redcarpet:
 extensions: [
  "no_intra_emphasis",
  "fenced_code_blocks",
  "tables",
  "strikethrough"
 ]
pygments: false

exclude:
- 'vendor' # for vendored gems
- 'Gemfile'
- 'Gemfile.lock'
- 'Rakefile'
- 'Gruntfile.js'
- 'package.json'
